# Generated by Django 4.2.17 on 2025-01-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_2fa_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
