# Generated by Django 4.2.17 on 2025-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://i.ibb.co/xqNGxfX/default.png'),
        ),
    ]
