# Generated by Django 4.2.17 on 2025-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='crypto_balances',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
