# Generated by Django 4.2.17 on 2025-03-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_wallet_crypto_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='crypto_balances',
            field=models.JSONField(default=dict),
        ),
    ]
