# Generated by Django 4.2.17 on 2025-02-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0012_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy Cryptocurrency'), ('SELL', 'Sell Cryptocurrency')], max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('LIMIT_BUY', 'Limit Buy'), ('LIMIT_SELL', 'Limit Sell')], max_length=10)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=15)),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('filled_amount', models.DecimalField(decimal_places=8, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.wallet')),
            ],
        ),
    ]
